name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Сборка JAR-файла
        run: |
          mvn -B install --file CRUD/pom.xml
          mvn -B package --file CRUD/pom.xml

      - name: Установка Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Копирование docker-compose.yml и .env
        run: |
          cp CRUD/docker-compose.yml .
          cp CRUD/.env .

      - name: Логин в Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Сборка и пуш Docker-образа
        run: |
          sudo docker-compose down
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-web:latest
          sudo docker-compose up -d --build

      - name: Copy docker-compose and env file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "CRUD/docker-compose.yml,CRUD/.env"
          target: "/home/${{ secrets.SERVER_USER }}/"

      - name: Деплой на сервере
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker-compose down
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-web:latest
            docker-compose up -d --build